// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhdkojtwvyunlooctwme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZGtvanR3dnl1bmxvb2N0d21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjI2MTksImV4cCI6MjA2NTQzODYxOX0._tQb78s87rMMeoGcm5gAS5KEU8jsjnAFkeJ3hdyvCNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);